{% set name = "console_bridge" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9f024a38f0947ed9fa67f58829980c2d90d84740e6de20d75cb00866f07a7a0b

build:
  number: 1
  skip: true # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }} # [unix or osx]
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT # [unix or osx]
    - if exist %PREFIX%\\Library\\CMake\\console_bridge-targets.cmake (exit 0) else (exit 1) # [win]
    - if exist %PREFIX%\\Library\\CMake\\console_bridge-config.cmake (exit 0) else (exit 1) # [win]

about:
  home: http://github.com/ros/console_bridge
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A ROS-independent package for logging that seamlessly pipes into rosconsole/rosout for ROS-dependent packages.'
  dev_url: https://github.com/ros/console_bridge

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
