travis:
  secure:
    BINSTAR_TOKEN: 1rc1Gb4sQLQAgpOyUaJuqFZt08bjhWmWcSMln3BmE38Tg4VdAQfl2301sYISe4tRF1cFCw3rWGszlMz7Ah+0UizyVfyGffo7qxbQ6/+ChAiGl9mHslcas4wQcfM3bZQIQ6n2SAX0AKoDNQnkpF1Wsd3JOrmKMuVxYNiN/0RL/+h2Jj+N+mxIOdPqlzmlXIAOUa0wKc/pHiuj1PEex/ewWKgC2A0KHxJPA6STgpn2jt3N2Td3dpbE6lG36UtRMCm46wMjUv/UcsAT8AlKs4V55j1UWFg55X8rIfcQJ6SafIsXDjedsVOi6EdAkdIw9uOBp1CQ+pXleNB22DJMSXJubc83ebUQkcmhdoETC/b/hY54h0RYrX75e4c8xdN0gixMmV9dfWB0B+iQ8flAW2UfFL4+zzLNJ5yWm+bumVTjT4EFnC92/Kr07OSSbs8m0HOw0n8IKhA6aU0Mp1R7jVt9He2QGN86A2hpzqHDpnVtOTrsRlnNtOFr1nvselMnwnGFzdiknxOZKgSlJVMfQ1Rlo2Afo9EnkF6SKQUG8srwvM4BizswXwlAXBtMgnqjj7OMpI8vM8uqa193jtm2Q2/rNbJdWjAwyT/RRXey10hNTUqyjaCxxUaD+0zsiWReGRVslAo+FFdK31uxSoX0jvSs5c1ODHO/v6iWujA8cEn9l84=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
